---
orbs:
  release-management: salesforce/npm-release-management@4.16.1
version: 2.1
jobs:
  node-16: &test
    docker:
      - image: node:16
    working_directory: ~/cli
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
            - v1-npm-{{checksum ".circleci/config.yml"}}
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run: ./bin/run --help
      - run:
          name: Testing
          command: yarn test
  node-12:
    <<: *test
    docker:
      - image: node:12
  node-14:
    <<: *test
    docker:
      - image: node:14
  cache:
    <<: *test
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
          paths:
            - ~/cli/node_modules
            - /usr/local/share/.cache/yarn
            - /usr/local/share/.config/yarn
  release:
    docker:
      - image: circleci/node:12.10
    steps:
      - checkout
      - restore_cache: *restore_cache
      - install-sf-release
      - install-sfdx-trust
      - run:
          name: Install plugin dependencies
          command: yarn
      - run:
          name: Install awscli
          command: |
            sudo apt-get update
            sudo apt-get install -y awscli
      - run:
          name: Set credentials
          command: |
            echo //registry.npmjs.org/:_authToken=${SF_PUBLISH_NPM_TOKEN} > ~/.npmrc
            echo unsafe-perm = true >> ~/.npmrc
            echo ${SALESFORCE_KEY} | base64 --decode > ~/salesforce-cli.key
      - run:
          name: Sign and publish
          command: ./bin/publish

workflows:
  version: 2
  "sf-plugin-functions":
    jobs:
      - node-16
      - node-14
      - node-12
      - cache:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - release:
          context: functions-cli
          requires:
            - node-16
            - node-14
            - node-12
